apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-deployment
  labels:
    app: receiver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
      - name: receiver
        image: multicast
        ports:
        - hostPort: 12345
          containerPort: 12345
          protocol: "UDP"
        args:
        - "-g"
        - "224.0.1.10:12345"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
