apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    role: server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: server
  template:
    metadata:
      labels:
        role: server
    spec:
      containers:
      - name: server
        image: multicast
        args:
        - "-s"
